debug: false
server:
  port: 8080
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      client:
        registration:
         google:
          client-id:
          client-secret:
          scope:
           - email
           - profile